/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARow: typeof import('ant-design-vue/es')['Row']
    ClinicalAckPage: typeof import('./src/components/clinical/ClinicalAckPage.vue')['default']
    ClinicalList: typeof import('./src/components/clinical/ClinicalList.vue')['default']
    ClinicalListItem: typeof import('./src/components/clinical/ClinicalListItem.vue')['default']
    ClinicalListView: typeof import('./src/components/clinical/ClinicalListView.vue')['default']
    ClinicalTab: typeof import('./src/components/clinical/ClinicalTab.vue')['default']
    FilterInput: typeof import('./src/components/commons/filter-input/FilterInput.vue')['default']
    FilterSelection: typeof import('./src/components/commons/filter-input/FilterSelection.vue')['default']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortSelection: typeof import('./src/components/commons/filter-input/SortSelection.vue')['default']
    Tabs: typeof import('./src/components/commons/tabs/Tabs.vue')['default']
  }
}
